# Generated by Django 4.2 on 2023-04-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_cartitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='mage',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='картинка'),
        ),
    ]
