# Generated by Django 4.2 on 2023-04-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_news_mage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='mage',
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='loading/', verbose_name='картинка'),
        ),
    ]
